"""
Consent Intent Detector Module for Data Principal Consent Manager.

Provides explainable, weighted contextual scoring to determine whether
an incoming email is a genuine Data Processing Consent Request before
any consent request record is created in the database.

Architecture:
Gmail search -> candidate email -> system-generated filter -> consent intent detector -> classification -> consent request
"""

import re
import logging
from typing import Dict, Any, List, Tuple

logger = logging.getLogger(__name__)

# Classification constants
CONSENT_REQUEST = "CONSENT_REQUEST"
NOT_CONSENT = "NOT_CONSENT"
AMBIGUOUS = "AMBIGUOUS"

# Confidence levels
HIGH = "HIGH"
MEDIUM = "MEDIUM"
LOW = "LOW"

# Score Thresholds
THRESHOLD_CONSENT_REQUEST = 6
THRESHOLD_AMBIGUOUS_MIN = 3


def detect_consent_intent(
    subject: str,
    body: str,
    sender: str = "",
    fiduciary_name: str = ""
) -> Dict[str, Any]:
    """
    Evaluates contextual evidence in an email to classify its consent intent.

    Returns:
    {
        "is_consent_request": bool,
        "classification": "CONSENT_REQUEST" | "NOT_CONSENT" | "AMBIGUOUS",
        "score": int,
        "confidence": "HIGH" | "MEDIUM" | "LOW",
        "reasons": list[str]
    }
    """
    subject_str = (subject or "").strip()
    body_str = (body or "").strip()
    sender_str = (sender or "").strip().lower()
    fid_str = (fiduciary_name or "").strip().lower()

    combined_text = f"{subject_str}\n{body_str}"
    combined_lower = combined_text.lower()
    subject_lower = subject_str.lower()
    body_lower = body_str.lower()

    score = 0
    reasons: List[str] = []
    positive_categories: List[str] = []

    # ─────────────────────────────────────────────────────────────────────────
    # 1. STRONG NEGATIVE INDICATORS (Heavily penalized or immediate disqualifier)
    # ─────────────────────────────────────────────────────────────────────────

    # A. System-Generated DPDP Receipts / Responses / Audit Records
    system_receipt_patterns = [
        r"=== digital consent status update ===",
        r"sha-256 integrity hash",
        r"generated by data principal consent manager",
        r"secured by data principal consent manager",
        r"dispatched via data principal consent manager",
        r"=== privacy grievance notice ===",
        r"\bdecision:\s*consent (granted|denied)\b",
        r"\bdigital consent status confirmation\b",
        r"\bdpdp consent response\b",
        r"\bconsent (has been )?(granted|denied|withdrawn)\b"
    ]
    for pat in system_receipt_patterns:
        if re.search(pat, combined_lower):
            score -= 15
            reasons.append("system-generated DPDP status receipt or decision confirmation")
            break

    # B. Password Reset / Account Security Alerts
    pwd_security_patterns = [
        r"\b(password reset|reset (your )?password|change (your )?password|temporary password|forgot (your )?password)\b",
        r"\b(security alert|new login detected|suspicious (sign-?in|activity|login)|unrecognized device|login alert|two-factor authentication|2fa code)\b",
        r"\b(account recovery|access credentials|unauthorized access attempt)\b"
    ]
    for pat in pwd_security_patterns:
        if re.search(pat, combined_lower):
            score -= 10
            reasons.append("password reset or account security alert detected")
            break

    # C. OTP / Verification Codes / 2FA
    otp_patterns = [
        r"\b(one-?time password|otp\b|verification code|security code|your (verification|login|otp) code is|use code \d{4,8}|do not share this (code|otp|password))\b",
        r"\b(enter this code|is your secret code|valid for \d+ minutes)\b"
    ]
    for pat in otp_patterns:
        if re.search(pat, combined_lower):
            score -= 10
            reasons.append("one-time password (OTP) or authentication code detected")
            break

    # D. Invoices, Billing, Order & Shipping Notifications
    invoice_patterns = [
        r"\b(invoice (number|no\.?|#)|receipt for order|order confirmation|payment receipt|shipping confirmation|order details|amount due|billing statement|tax invoice|track your package|your order has shipped)\b"
    ]
    for pat in invoice_patterns:
        if re.search(pat, combined_lower):
            score -= 8
            reasons.append("transactional invoice, order, or shipping notification")
            break

    # E. Generic Newsletters, Promotional Marketing & Digest Emails
    newsletter_patterns = [
        r"\b(newsletter|weekly digest|monthly digest|unsubscribe from this list|manage your email preferences|special discount|limited time offer|flash sale|view this email in your browser|to unsubscribe click here)\b",
        r"\b(exclusive offer|promotional discount|sale ends|shop now|buy now|promotional deal)\b"
    ]
    for pat in newsletter_patterns:
        if re.search(pat, combined_lower):
            score -= 6
            reasons.append("generic newsletter or promotional marketing email")
            break

    # F. Automated Out-of-Office / Delivery Status Notifications
    auto_reply_patterns = [
        r"\b(out of office|auto-?reply|automatic reply|delivery status notification|undelivered mail|mailer-daemon)\b"
    ]
    for pat in auto_reply_patterns:
        if re.search(pat, combined_lower):
            score -= 10
            reasons.append("automated out-of-office or delivery failure notification")
            break

    # G. Informational Policy Updates Without Consent Request Action
    policy_update_patterns = [
        r"\b(privacy policy (has been )?updat(ed)?|terms of service update|we('ve| have) updated our (privacy policy|terms)|notice of (policy )?update|no action is required( on your part)?|for your information only)\b"
    ]
    for pat in policy_update_patterns:
        if re.search(pat, combined_lower):
            score -= 4
            reasons.append("informational privacy policy update without consent request action")
            break

    # H. IT Operations / System Maintenance Notices
    maintenance_patterns = [
        r"\b(server maintenance|system maintenance|scheduled downtime|scheduled maintenance|facility announcement|maintenance advisory)\b"
    ]
    for pat in maintenance_patterns:
        if re.search(pat, combined_lower):
            score -= 6
            reasons.append("IT operations or system maintenance advisory notice")
            break

    # ─────────────────────────────────────────────────────────────────────────
    # 2. STRONG POSITIVE INDICATORS (Weighted Contextual Evidence)
    # ─────────────────────────────────────────────────────────────────────────

    has_explicit_request = False
    has_authorization = False
    has_data_processing = False
    has_purpose = False
    has_attributes = False

    # A. Explicit Consent Request Language (+4)
    # e.g., "requesting consent", "requests your consent", "please provide your consent", "grant consent"
    # A. Explicit Consent Request Language (+4)
    # e.g., "requesting consent", "requests your consent", "please provide your consent", "grant consent"
    explicit_request_patterns = [
        r"\b(request(s|ing)? (your )?(digital |explicit |express )?consent)\b",
        r"\b(please (grant|provide|give|submit) (your )?(digital |explicit |express )?consent)\b",
        r"\b(seeking (your )?(digital |explicit |express )?consent|seek (your )?consent)\b",
        r"\b(require(s)? (your )?(digital |explicit |express )?consent)\b",
        r"\b(consent is requested|consent request notice|consent request for|consent request:)\b",
        r"\b(action required:\s*(grant )?data consent|grant(ing)? (data )?consent)\b",
        r"\b(processing consent|consent verification notice|consent verification)\b",
        r"\b(kyc (identity )?(verification )?notice|account verification notice)\b",
        r"\b(consent request details)\b"
    ]
    for pat in explicit_request_patterns:
        if re.search(pat, combined_lower):
            score += 4
            has_explicit_request = True
            positive_categories.append("explicit_request")
            reasons.append("explicit consent request language")
            break

    # B. Permission or Authorization to Process Data (+3)
    # e.g., "authorize us to process", "permission to collect and process", "consent to process"
    authorization_patterns = [
        r"\b(authoriz(e|ing) (us|[a-z0-9\s\-]+) to (process|collect|access|fetch|verify|share))\b",
        r"\b(permission to (process|collect|access|use|store|share|fetch|verify))\b",
        r"\b(consent to (process|collect|access|use|store|share|fetch|verify))\b",
        r"\b(consent for ([a-z0-9\s\-]+ )?(data processing|processing|verification|kyc|records|promotional))\b",
        r"\b(credit assessment|loan assessment|credit score processing)\b",
        r"\b(require(s)? your authorization|grant authorization|provide authorization)\b",
        r"\b(authorization:\s*[a-z0-9\s\-]+study|[a-z0-9\s\-]+authorization)\b"
    ]
    for pat in authorization_patterns:
        if re.search(pat, combined_lower):
            score += 3
            has_authorization = True
            positive_categories.append("authorization")
            reasons.append("permission or authorization to process data")
            break

    # C. Data Processing Operations / Statutory Context (+2)
    # e.g., "processing personal data", "collect and process", "DPDP Act"
    data_ops_patterns = [
        r"\b(process(ing)? (of )?(your )?personal (data|information))\b",
        r"\b(collect(ion)? and process(ing)?|collect, process|storage and processing)\b",
        r"\b(shar(e|ing)|disclos(e|ure)|transfer) (of )?(your )?(personal )?(data|records|grades)\b",
        r"\b(verify your (government identity|identity|pan|aadhaar))\b",
        r"\b(credit assessment and bureau consent|assessment and credit score processing)\b",
        r"\b(dpdp act|digital personal data protection( act)?|data protection act 2023|section 6)\b",
        r"\b(statutory requirements|rbi mandatory kyc)\b"
    ]
    for pat in data_ops_patterns:
        if re.search(pat, combined_lower):
            score += 2
            has_data_processing = True
            positive_categories.append("data_operations")
            reasons.append("data collection, processing operations, or statutory framework identified")
            break

    # D. Stated Processing Purpose (+2)
    # e.g., "purpose of data processing:", "in order to process", specific business purpose
    purpose_patterns = [
        r"\b(purpose of (data )?processing|purpose:|processed for:|in order to process|for the purpose of)\b",
        r"\b(for ([a-z0-9\s\-]+ )?(student services|academic records|degree verification|account opening|savings account|kyc verification|cashless treatment|credit assessment|loan sanction|loan disbursement|personal loan|placement profile|employment verification|identity verification|clinical research|background verification))\b",
        r"\b(for (heart clinic|banking services|fintech lending|pf account processing|recruitment partners|promotional communications|promotional offers))\b",
        r"\b(to process (your )?([a-z0-9\s\-]+ )?(credit line|loan|application|account))\b"
    ]
    for pat in purpose_patterns:
        if re.search(pat, combined_lower):
            score += 2
            has_purpose = True
            positive_categories.append("purpose")
            reasons.append("processing purpose identified")
            break

    # E. Identifiable Personal-Data Attributes (+2 or +3)
    # Explicit attribute list bullet points (+3)
    explicit_attr_list_patterns = [
        r"\b(data requested:|requested data:|requested attributes:)\b",
        r"(-\s*(full name|date of birth|mobile number|email address|enrollment number|academic records))\b"
    ]
    matched_explicit_list = any(re.search(pat, combined_lower) for pat in explicit_attr_list_patterns)
    if matched_explicit_list:
        score += 3
        has_attributes = True
        positive_categories.append("attributes")
        reasons.append("explicit list of personal data attributes identified")
    else:
        # Check specific personal data attribute tokens
        attribute_tokens = [
            r"\b(pan|pan card)\b",
            r"\b(aadhaar|aadhaar number)\b",
            r"\b(cibil|cibil credit score|credit score)\b",
            r"\b(medical records|medical history|treatment history|medical treatment history|health records|medical health records)\b",
            r"\b(diagnostic (lab )?(medical )?reports|diagnostic test reports|lab reports)\b",
            r"\b(health insurance|insurance policy)\b",
            r"\b(academic records|student records|graduation certificates|semester grade sheets|academic grades|grades)\b",
            r"\b(enrollment number|roll number|student id)\b",
            r"\b(examination results|marks)\b",
            r"\b(bank account( statement)?|banking transaction history|annual income)\b",
            r"\b(blood test results|genetic markers|medical diagnosis)\b",
            r"\b(access card records|visitor log details|employee badge id)\b"
        ]
        attr_matches = sum(1 for pat in attribute_tokens if re.search(pat, combined_lower))
        if attr_matches >= 2:
            score += 2
            has_attributes = True
            positive_categories.append("attributes")
            reasons.append("personal data attributes identified")
        elif attr_matches == 1:
            score += 1
            has_attributes = True
            positive_categories.append("attributes")
            reasons.append("personal data attributes identified")

    # F. Data Principal Rights / Withdrawal Language (+1)
    # e.g., "right to withdraw", "revoke consent", "granular consent choices"
    rights_patterns = [
        r"\b(right to withdraw|withdraw(al)? (of )?(your )?consent|revoke (your )?consent|granular consent choices|consent choices|manage (your )?consent)\b"
    ]
    for pat in rights_patterns:
        if re.search(pat, combined_lower):
            score += 1
            positive_categories.append("rights")
            reasons.append("consent withdrawal or data principal rights language identified")
            break

    # G. Interactive Consent Action Link / Mechanism (+1)
    # e.g., /request/tok_xxx, "review and submit your decision"
    mechanism_patterns = [
        r"/request/[a-zA-Z0-9_\-]+",
        r"\b(click (here|the button below) to review (and submit|the privacy notice)|review and submit your decision|configure your granular consent)\b"
    ]
    for pat in mechanism_patterns:
        if re.search(pat, combined_lower):
            score += 1
            positive_categories.append("action_mechanism")
            reasons.append("interactive consent action mechanism or decision link identified")
            break

    # ─────────────────────────────────────────────────────────────────────────
    # 3. CONTEXTUAL EVIDENCE GUARD
    # ─────────────────────────────────────────────────────────────────────────
    # A keyword match alone (subject having 'Consent', 'Action Required', 'Privacy',
    # 'Notice', 'DPDP') must NOT create a consent request without contextual proof.
    isolated_subject_keywords = ["consent", "action required", "privacy", "notice", "dpdp"]
    has_subject_keywords = any(kw in subject_lower for kw in isolated_subject_keywords)

    # Core contextual requirements for a valid consent request
    has_core_evidence = (
        has_explicit_request or
        has_authorization or
        (has_data_processing and (has_attributes or has_purpose))
    )

    if has_subject_keywords and not has_core_evidence and score > 0:
        reasons.append("subject keyword match lacks sufficient contextual consent request evidence")

    # ─────────────────────────────────────────────────────────────────────────
    # 4. FINAL CLASSIFICATION & CONFIDENCE SCORING
    # ─────────────────────────────────────────────────────────────────────────
    if score >= THRESHOLD_CONSENT_REQUEST and has_core_evidence:
        classification = CONSENT_REQUEST
        is_consent = True
        confidence = HIGH if score >= 8 else MEDIUM
    elif score >= THRESHOLD_AMBIGUOUS_MIN:
        # Score is moderate (3-5) or lacks mandatory core request evidence
        classification = AMBIGUOUS
        is_consent = False
        confidence = MEDIUM
    else:
        classification = NOT_CONSENT
        is_consent = False
        confidence = HIGH if score <= 0 else MEDIUM

    if not reasons:
        if is_consent:
            reasons.append("sufficient contextual consent request indicators")
        else:
            reasons.append("insufficient consent request evidence")

    logger.debug(
        f"[ConsentIntentDetector] score={score}, classification={classification}, "
        f"confidence={confidence}, reasons={reasons}"
    )

    return {
        "is_consent_request": is_consent,
        "classification": classification,
        "score": score,
        "confidence": confidence,
        "reasons": reasons
    }
