import os
import sys
import unittest
import uuid

# Ensure backend directory and tests directory are in python search path
TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.abspath(os.path.join(TESTS_DIR, ".."))
for p in [TESTS_DIR, BACKEND_DIR]:
    if p not in sys.path:
        sys.path.insert(0, p)

from test_helper import create_isolated_test_db, destroy_isolated_test_db, assert_not_production_db
from main import app, get_db
from fastapi.testclient import TestClient


class TestSystemGeneratedEmailFilter(unittest.TestCase):
    """
    Test suite verifying that system-generated receipts/replies/notifications
    are ignored without polluting the database, while genuine incoming
    fiduciary requests (healthcare, banking, education, fintech) are properly ingested.
    """

    @classmethod
    def setUpClass(cls):
        cls.test_db_path = create_isolated_test_db()
        assert_not_production_db()
        cls.webhook_secret = os.getenv("GMAIL_WEBHOOK_SECRET", "test-secret-filter-123")
        os.environ["GMAIL_WEBHOOK_SECRET"] = cls.webhook_secret
        cls.client = TestClient(app)

    @classmethod
    def tearDownClass(cls):
        destroy_isolated_test_db(cls.test_db_path)

    def setUp(self):
        assert_not_production_db()
        self.headers = {"X-Webhook-Secret": self.webhook_secret}

    def test_system_generated_consent_receipt_is_ignored(self):
        """
        A system-generated status receipt with 'DIGITAL CONSENT STATUS UPDATE'
        and 'SHA-256 Integrity Hash' must be ignored and create 0 rows in DB.
        """
        unique_msg_id = f"test_sys_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "compliance@education.com",
            "to_address": "Data Principal <user@example.com>",
            "subject": "Re: Action Required: Student Academic Records Consent",
            "body_text": (
                "=== DIGITAL CONSENT STATUS UPDATE ===\n"
                "Decision: CONSENT GRANTED\n"
                "Notice ID: NTC-2026-TEST-101\n"
                "Artifact ID: CNST-2026-9999\n"
                "SHA-256 Integrity Hash: sha256:abc123456789\n"
                "Generated by Data Principal Consent Manager\n"
            ),
            "fiduciary_name": "ABC Institute",
            "message_id": unique_msg_id,
            "thread_id": "thd_sys_1"
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertTrue(data.get("ignored"), f"Expected ignored=True, got: {data}")
        self.assertEqual(data.get("reason"), "system_generated_message")

        # Verify no consent request was created
        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 0, "No consent_request should be created for system-generated receipts")

    def test_subject_re_consent_with_decision_markers_is_ignored(self):
        """
        Subject starting with 'Re: Consent' with decision markers must be ignored.
        """
        unique_msg_id = f"test_sys_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "fiduciary@company.com",
            "to_address": "user@example.com",
            "subject": "Re: Consent for Promotional Communications",
            "body_text": (
                "CONSENT DENIED\n"
                "The Data Principal has denied your request.\n"
                "DPDP Consent Response"
            ),
            "fiduciary_name": "Promotions Co",
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertTrue(data.get("ignored"))
        self.assertEqual(data.get("reason"), "system_generated_message")

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 0)

    def test_sender_dpdp_privacy_portal_is_ignored(self):
        """
        Any email where the sender or fiduciary name is 'DPDP Privacy Portal' must be ignored.
        """
        unique_msg_id = f"test_sys_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "DPDP Privacy Portal <compliance@general.com>",
            "to_address": "user@example.com",
            "subject": "Re: Consent for Marketing",
            "body_text": "Random body text from portal",
            "fiduciary_name": "DPDP Privacy Portal",
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertTrue(data.get("ignored"))
        self.assertEqual(data.get("reason"), "system_generated_message")

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 0)

    def test_automated_dp_statutory_notice_is_ignored(self):
        """
        Automated DP statutory notice emails sent to the Data Principal by Apps Script
        must not loop back into a new consent request.
        """
        unique_msg_id = f"test_sys_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "user@gmail.com",
            "to_address": "user@gmail.com",
            "subject": "New Consent Request: Apollo Hospital",
            "body_text": (
                "New Consent Request\n\n"
                "Fiduciary: Apollo Hospital\n"
                "Purpose: Healthcare Data Processing\n\n"
                "Review Consent Request: http://localhost:5173/request/tok_123\n\n"
                "This is an automated statutory notice under the Digital Personal Data Protection (DPDP) Act 2023."
            ),
            "fiduciary_name": "Apollo Hospital",
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertTrue(data.get("ignored"))
        self.assertEqual(data.get("reason"), "system_generated_message")

    def test_genuine_healthcare_request_is_ingested(self):
        """
        Genuine incoming healthcare consent request must be accepted and classified under Healthcare.
        """
        unique_msg_id = f"test_real_health_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "Apollo Health Center <compliance@apollohealth.org>",
            "to_address": "Patient Sharma <patient@example.com>",
            "subject": "Action Required: Consent for Healthcare Data Processing",
            "body_text": (
                "Dear Patient,\n\n"
                "Apollo Health Center requires your consent for processing diagnostic lab reports "
                "and medical treatment history in accordance with the DPDP Act 2023.\n\n"
                "Please review and submit your decision."
            ),
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertFalse(data.get("ignored", False), f"Genuine healthcare request should NOT be ignored: {data}")
        self.assertEqual(data.get("domain"), "Healthcare")
        self.assertTrue(data.get("token", "").startswith("tok_"))

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 1, "Genuine healthcare request must create exactly 1 consent_request")

    def test_genuine_banking_request_is_ingested(self):
        """
        Genuine incoming banking KYC consent request must be accepted and classified under Banking.
        """
        unique_msg_id = f"test_real_bank_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "State Bank Operations <kyc-notice@sbi-online.in>",
            "to_address": "Account Holder <user@example.com>",
            "subject": "Action Required: Consent for Bank KYC and Account Verification",
            "body_text": (
                "Dear Customer,\n\n"
                "We require your explicit consent to verify your PAN, Aadhaar number, and annual income "
                "for opening your digital savings bank account."
            ),
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertFalse(data.get("ignored", False))
        self.assertEqual(data.get("domain"), "Banking")

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 1)

    def test_genuine_education_request_is_ingested(self):
        """
        Genuine incoming education records request must be accepted and classified under Education.
        """
        unique_msg_id = f"test_real_edu_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "Delhi Institute of Technology <registrar@dit.edu.in>",
            "to_address": "Student <student@example.com>",
            "subject": "Action Required: Student Academic Records Consent",
            "body_text": (
                "Dear Student,\n\n"
                "Please provide your consent for university degree verification and semester grade sheets."
            ),
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertFalse(data.get("ignored", False))
        self.assertEqual(data.get("domain"), "Education")

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 1)

    def test_genuine_fintech_request_is_ingested(self):
        """
        Genuine incoming fintech request must be accepted and classified under FinTech.
        """
        unique_msg_id = f"test_real_fintech_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "PayCredit Lending <privacy@paycredit.com>",
            "to_address": "User <user@example.com>",
            "subject": "Action Required: FinTech Credit Assessment and Bureau Consent",
            "body_text": (
                "Dear Applicant,\n\n"
                "To process your instant credit line, please authorize PayCredit to fetch your CIBIL credit score "
                "and banking transaction history."
            ),
            "message_id": unique_msg_id,
        }

        res = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res.status_code, 200)
        data = res.json()

        self.assertFalse(data.get("ignored", False))
        self.assertEqual(data.get("domain"), "FinTech")

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 1)

    def test_genuine_request_idempotency_preserved(self):
        """
        Posting the same genuine incoming request twice returns the same token and request ID.
        """
        unique_msg_id = f"test_real_idemp_{uuid.uuid4().hex[:12]}"
        payload = {
            "from_address": "Apollo Health Center <compliance@apollohealth.org>",
            "to_address": "Patient <patient@example.com>",
            "subject": "Action Required: Consent for Healthcare Data Processing",
            "body_text": "Healthcare consent request details...",
            "message_id": unique_msg_id,
        }

        res1 = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res1.status_code, 200)
        data1 = res1.json()

        res2 = self.client.post("/api/gmail-webhook", json=payload, headers=self.headers)
        self.assertEqual(res2.status_code, 200)
        data2 = res2.json()

        self.assertEqual(data1["token"], data2["token"])
        self.assertEqual(data1["id"], data2["id"])

        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM consent_requests WHERE message_id = ?;", (unique_msg_id,))
        count = c.fetchone()[0]
        conn.close()
        self.assertEqual(count, 1, "Idempotency must prevent duplicate consent_requests")


if __name__ == "__main__":
    unittest.main()
